#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  button3,        sensorTouch)
#pragma config(Sensor, dgtl11, encoder,        sensorQuadEncoder)
#pragma config(Motor,  port1,           mainMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int level1 = 0;
const int level2 = 550;
const int level3 = 1100;

const int speed = 100;
const int slowSpeedUp = 30;
const int slowSpeedDown = 23;

const int sharpness = 100;
const int slowSharpness = 5;

int target;

task main() {
	target = SensorValue(encoder);

	while (true) {
		if (SensorValue[button1]) {
			target = level1;
		} else if (SensorValue[button2]) {
			target = level2;
		} else if (SensorValue[button3]) {
			target = level3;
		}

		if (SensorValue[encoder] < target - sharpness) {
			startMotor(mainMotor, speed);
		} else if (SensorValue[encoder] > target + sharpness) {
			startMotor(mainMotor, -speed);
		} else if (SensorValue[encoder] < target - slowSharpness) {
			startMotor(mainMotor, slowSpeedUp);
		} else if (SensorValue[encoder] > target + slowSharpness) {
			startMotor(mainMotor, -slowSpeedDown);
		} else {
			stopMotor(mainMotor);
		}
	}
}
